### ISSUE TITLE
 [Error: unknown error] { code: 500, message: 'unknown error' }

### ISSUE THREAD

**Issue by 377123** [serverless-components/tencent-postgresql#3]
chengyun:DB ring$ sls --debug

  DEBUG ─ Resolving the template's static variables.
  DEBUG ─ Collecting components from the template.
  DEBUG ─ Downloading any NPM components found in the template.
  DEBUG ─ Analyzing the template's components dependencies.
  DEBUG ─ Creating the template's components graph.
  DEBUG ─ Syncing template state.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Start create DB instance serverlessDb...

  error:
  [Error: unknown error] { code: 500, message: 'unknown error' }

  3s › MyPostgreSQL › Error: unknown error

**Comment by tinafangkunding** [comment]
感谢反馈，请问您的yaml配置文件是怎样的？当前是在哪个地域和可用区创建的实例呢

**Comment by yugasun** [comment]
@377123 可以提供下你的yml吗？目前此组件支持区域为：

```
ap-guangzhou-2
ap-beijing-3
ap-shanghai-2
```

**Comment by 377123** [comment]
好了 是区域问题
