### ISSUE TITLE
vpc network information incorrect.

### ISSUE THREAD

**Issue by 798714773** [serverless-components/tencent-postgresql#8]
vpc配置要怎么填，能否详细说明一下
一直没明白的是，数据库创建在哪里了。可以外网访问吗？可以用命令行连接吗？如何操作数据库呢？一些数据迁移的问题怎么处理呢？

**Comment by tinafangkunding** [comment]
hi ，您好

1. vpc 的配置，目前有两种方式：
第一种是去云账户的控制台，查询已有的 vpc 和子网，获取 id 信息，然后填入到 serverless.yml 里面
第二种是直接搭配 vpc 组件创建一个新的 vpc，然后把输出的结果通过变量的方式传入到 DB 的 yaml 里面，参考 https://cloud.tencent.com/document/product/1154/43009 里的用法

> 另外，这块要注意数据库的 vpc 和 函数的 vpc 要保持一致才可以内网访问

2. 数据库默认会创建在 VPC 里面，预计 8 月初会在腾讯云的数据库控制台中展示。

3. 如果要开启数据库的外网访问，修改这个配置就可以
```
  extranetAccess: true
```
4. 连接 DB 的操作主要是在函数中完成的，命令行主要做的控制流的操作，比如创建和初始化 DB 实例
5. 对数据库的数据流操作，可以在云函数中连接 DB，然后进行正常的创建库表，CRUD 就可以的。参考代码
https://github.com/serverless-components/tencent-examples/blob/master/fullstack/api/controller/user.js
